allowBuilds:
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

blockExoticSubdeps: true

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 1440 # 1 Day

minimumReleaseAgeExclude:
  - 'shadcn-svelte@1.2.5'

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 525600 # 1 Year
